name: ghost_scale
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  tflite_flutter: ^0.12.1
  image_picker: ^1.1.2
  gal: ^2.3.0
  permission_handler: ^11.3.1
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  google_fonts: ^6.2.1
  introduction_screen: ^3.1.14
  before_after: ^3.0.0
  path_provider: ^2.1.4
  image: ^4.2.0
  dio: ^5.9.0
  wakelock_plus: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/screenshots/app_showcase.png" # Using screenshot as fallback icon source
  min_sdk_android: 21

flutter:
  uses-material-design: true
  assets:
    - assets/models/
